CREATE TABLE IF NOT EXISTS users (
id uuid PRIMARY KEY,
email VARCHAR(225) NOT NULL,
password VARCHAR(125) NOT NULL,
salt VARCHAR(125) NOT NULL,
created_at TIMESTAMPTZ DEFAULT NOW(),
updated_at TIMESTAMPTZ DEFAULT NOW()
)