# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  coverage:
    name: coverage
runs-on: macos-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: car_dealer_db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 54321:5432
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: '4.0.9'
    - run: npm install
    - run: npm install nyc -g
      env:
        TEST_DATABASE_URL: ${{secret.TEST_DATABASE_URL}}
        CAR_DEALER_JWT_SECRET: ${{secret.TEST_DATABASE_URL}}
        CAR_DEALER_NODE_ENV: 'test'
        TSR_AWS_ACCESS_KEY: ${{secret.TSR_AWS_ACCESS_KEY}}
        TSR_AWS_SECRET_KEY: ${{secret.TSR_AWS_SECRET_KEY}}
        TSR_AWS_BUCKET:    ${{secret.TSR_AWS_BUCKET}}
    - run: npm run test
        debug: true
