# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: mypass
          POSTGRES_DB: coverageawakedb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 54321:5432
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: '4.0.9'
    - run: npm install
    - run: npm install nyc -g
      env:
        CC_TEST_REPORTER_ID: '21cd1204d403962ea55408784f329eb5d7c03b2993964f0ce8aaeb99d5711031'
        TEST_DATABASE_URL:    'postgres://fortune:123456@localhost:5432/car_dealer_db_test'
        CAR_DEALER_JWT_SECRET: '@hdhd%w&91jqQ32nps'
        CAR_DEALER_NODE_ENV: 'test'
        TSR_AWS_ACCESS_KEY:  'AKIAJWM3Z6ECSAXZNXZQ'
        TSR_AWS_SECRET_KEY:  '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'
        TSR_AWS_BUCKET:      'thesaint-autos'
      with:
        coverageCommand: npm run test
        debug: true
